fix: header and footer inside body

diff --git a/.github/workflows/publish-to-github-pages.yml b/.github/workflows/publish-to-github-pages.yml
--- a/.github/workflows/publish-to-github-pages.yml
+++ b/.github/workflows/publish-to-github-pages.yml
@@ -1,40 +1,87 @@
-name: Publish to GitHub pages
+name: Deploy Next.js site to GitHub Pages
 
 on:
   push:
-    branches:
-      - main
+    branches: ['main']
+  workflow_dispatch:
 
+# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
 permissions:
   contents: read
   pages: write
   id-token: write
 
+# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
+# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
 concurrency:
-  group: "pages"
+  group: 'pages'
   cancel-in-progress: false
 
 jobs:
   build:
     runs-on: ubuntu-latest
-
     steps:
-      - name: 🛎️ Checkout
-        uses: actions/checkout@v4
-
-      - name: Setup Node.js ⚙️ - Cache dependencies ⚡ - Install dependencies 🔧
-        uses: ./.github/workflows/setup-node
-
-      - name: ⚙️ Setup Pages
-        uses: actions/configure-pages@v4
+      - name: 🔐 Harden Runner
+        uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
         with:
-          static_site_generator: next
+          egress-policy: audit
+
+      - name: 🛎️ Checkout
+        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
+        with:
+          fetch-depth: 0
+
+      - name: 🔍 Detect package manager
+        id: detect-package-manager
+        run: |
+          if [ -f '${{ github.workspace }}/yarn.lock' ]; then
+            echo 'manager=yarn' >> $GITHUB_OUTPUT
+            echo 'command=install' >> $GITHUB_OUTPUT
+            echo 'runner=yarn' >> $GITHUB_OUTPUT
+            exit 0
+          elif [ -f '${{ github.workspace }}/package.json' ]; then
+            echo 'manager=npm' >> $GITHUB_OUTPUT
+            echo 'command=ci' >> $GITHUB_OUTPUT
+            echo 'runner=npx --no-install' >> $GITHUB_OUTPUT
+            exit 0
+          else
+            echo 'Unable to determine package manager'
+            exit 1
+          fi
+
+      - name: 🐢 Setup Node
+        uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8 # v4.0.1
+        with:
+          node-version: '20'
+          cache: ${{ steps.detect-package-manager.outputs.manager }}
+
+      - name: 📃 Setup GitHub Pages
+        uses: actions/configure-pages@1f0c5cde4bc74cd7e1254d0cb4de8d49e9068c7d #v4.0.0
+        # with:
+          # Automatically inject basePath in your Next.js configuration file and disable
+          # server side image optimization (https://nextjs.org/docs/api-reference/next/image#unoptimized).
+          # You may remove this line if you want to manage the configuration yourself.
+          # static_site_generator: next
+
+      - name: 🗃️ Restore cache
+        uses: actions/cache@ab5e6d0c87105b4c9c2047343972218f562e4319 # 4.0.1
+        with:
+          path: |
+            .next/cache
+          # Generate a new cache whenever packages or source files change.
+          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
+          # If source files changed but packages didn't, rebuild from a prior cache.
+          restore-keys: |
+            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-
+
+      - name: 📦 Install dependencies
+        run: ${{ steps.detect-package-manager.outputs.manager }} ${{ steps.detect-package-manager.outputs.command }}
 
       - name: 🏗️ Build with Next.js
-        run: npx next build
+        run: NEXT_TELEMETRY_DISABLED=1 ${{ steps.detect-package-manager.outputs.runner }} next build
 
       - name: 📡 Upload artifact
-        uses: actions/upload-pages-artifact@v3
+        uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa # 3.0.1
         with:
           path: ./out
 
@@ -42,11 +89,9 @@ jobs:
     environment:
       name: github-pages
       url: ${{ steps.deployment.outputs.page_url }}
-
     runs-on: ubuntu-latest
     needs: build
-
     steps:
-      - name: 🚀 Publish to GitHub Pages
+      - name: 🚀 Deploy to GitHub Pages
         id: deployment
-        uses: actions/deploy-pages@v4
+        uses: actions/deploy-pages@decdde0ac072f6dcbe43649d82d9c635fff5b4e4 # 4.0.4
